### PR TITLE
FIX: Read in TSV file

### PR DESCRIPTION
**Pull request by mortonjt**
The input TSV file accepted by songbird should not be reading in the first column as the header -- this is automatically handled by q2.

Test cases upcoming up.

### CODE REVIEW

**Comment by fedarko** [comment]
Thanks for the PR! But not quite sure I understand. Could you point to where in the code the issue is?

The closest thing I can think of is `supervised_rank_plot()` in [`rankratioviz/q2/_method.py`](https://github.com/fedarko/rankratioviz/blob/master/rankratioviz/q2/_method.py), but I just [fixed it recently](https://github.com/fedarko/rankratioviz/commit/d76e7234fdff9b92b844790c1d727afb74687313) to use the index as read by Q2.

**Comment by mortonjt** [comment]
yup - that's the one

I was able to get rankratioviz to run, but got this error when trying to
open in chrome.

[image: image.png]

**Comment by mortonjt** [comment]
Ok it actually works!  Found out that it was due to opening up locally, and
works when plugging directly online to q2 view

**Comment by fedarko** [comment]
can't see the image, but glad you got it working! Yeah, you can also view a local visualization by starting a server with e.g. `python3 -m http.server` and then opening up `localhost:[port number]` in the browser. IIRC empress works sorta similarly.

**Comment by mortonjt** [comment]
ok, looks like this is fixed closing.

**Pull request closed without merging**
